# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addWindow(object):
    def setupUi(self, addWindow):
        addWindow.setObjectName("addWindow")
        addWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(addWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainBackgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainBackgroundLabel.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.mainBackgroundLabel.setStyleSheet("\n"
"border-image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13 blurredsmall.png);")
        self.mainBackgroundLabel.setText("")
        self.mainBackgroundLabel.setObjectName("mainBackgroundLabel")
        self.gardLabelSing = QtWidgets.QLabel(self.centralwidget)
        self.gardLabelSing.setGeometry(QtCore.QRect(10, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gardLabelSing.setFont(font)
        self.gardLabelSing.setAlignment(QtCore.Qt.AlignCenter)
        self.gardLabelSing.setObjectName("gardLabelSing")
        self.translLabelSing = QtWidgets.QLabel(self.centralwidget)
        self.translLabelSing.setGeometry(QtCore.QRect(210, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.translLabelSing.setFont(font)
        self.translLabelSing.setAlignment(QtCore.Qt.AlignCenter)
        self.translLabelSing.setObjectName("translLabelSing")
        self.TransLabelSing = QtWidgets.QLabel(self.centralwidget)
        self.TransLabelSing.setGeometry(QtCore.QRect(410, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TransLabelSing.setFont(font)
        self.TransLabelSing.setAlignment(QtCore.Qt.AlignCenter)
        self.TransLabelSing.setObjectName("TransLabelSing")
        self.singMainLabel = QtWidgets.QLabel(self.centralwidget)
        self.singMainLabel.setGeometry(QtCore.QRect(90, 10, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.singMainLabel.setFont(font)
        self.singMainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.singMainLabel.setObjectName("singMainLabel")
        self.addBtnSing = QtWidgets.QPushButton(self.centralwidget)
        self.addBtnSing.setGeometry(QtCore.QRect(190, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addBtnSing.setFont(font)
        self.addBtnSing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtnSing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addBtnSing.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.addBtnSing.setFlat(False)
        self.addBtnSing.setObjectName("addBtnSing")
        self.cancelBtnSing = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtnSing.setGeometry(QtCore.QRect(320, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtnSing.setFont(font)
        self.cancelBtnSing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtnSing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtnSing.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.cancelBtnSing.setFlat(False)
        self.cancelBtnSing.setObjectName("cancelBtnSing")
        self.translLabelMulti = QtWidgets.QLabel(self.centralwidget)
        self.translLabelMulti.setGeometry(QtCore.QRect(210, 340, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.translLabelMulti.setFont(font)
        self.translLabelMulti.setAlignment(QtCore.Qt.AlignCenter)
        self.translLabelMulti.setObjectName("translLabelMulti")
        self.cancelBtnMulti = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtnMulti.setGeometry(QtCore.QRect(220, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtnMulti.setFont(font)
        self.cancelBtnMulti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtnMulti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtnMulti.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.cancelBtnMulti.setFlat(False)
        self.cancelBtnMulti.setObjectName("cancelBtnMulti")
        self.gardLabelMulti = QtWidgets.QLabel(self.centralwidget)
        self.gardLabelMulti.setGeometry(QtCore.QRect(10, 340, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gardLabelMulti.setFont(font)
        self.gardLabelMulti.setAlignment(QtCore.Qt.AlignCenter)
        self.gardLabelMulti.setObjectName("gardLabelMulti")
        self.transLabelMulti = QtWidgets.QLabel(self.centralwidget)
        self.transLabelMulti.setGeometry(QtCore.QRect(410, 340, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.transLabelMulti.setFont(font)
        self.transLabelMulti.setAlignment(QtCore.Qt.AlignCenter)
        self.transLabelMulti.setObjectName("transLabelMulti")
        self.addBtnMulti = QtWidgets.QPushButton(self.centralwidget)
        self.addBtnMulti.setGeometry(QtCore.QRect(90, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addBtnMulti.setFont(font)
        self.addBtnMulti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtnMulti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addBtnMulti.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.addBtnMulti.setFlat(False)
        self.addBtnMulti.setObjectName("addBtnMulti")
        self.transListMulti = QtWidgets.QListWidget(self.centralwidget)
        self.transListMulti.setGeometry(QtCore.QRect(410, 370, 181, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.transListMulti.setFont(font)
        self.transListMulti.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.transListMulti.setObjectName("transListMulti")
        self.addBtnListMulti = QtWidgets.QPushButton(self.centralwidget)
        self.addBtnListMulti.setGeometry(QtCore.QRect(410, 560, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.addBtnListMulti.setFont(font)
        self.addBtnListMulti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtnListMulti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addBtnListMulti.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.addBtnListMulti.setFlat(False)
        self.addBtnListMulti.setObjectName("addBtnListMulti")
        self.removeBtnListMulti = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtnListMulti.setGeometry(QtCore.QRect(510, 560, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.removeBtnListMulti.setFont(font)
        self.removeBtnListMulti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeBtnListMulti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.removeBtnListMulti.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.removeBtnListMulti.setFlat(False)
        self.removeBtnListMulti.setObjectName("removeBtnListMulti")
        self.multiMainLabel = QtWidgets.QLabel(self.centralwidget)
        self.multiMainLabel.setGeometry(QtCore.QRect(80, 280, 441, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.multiMainLabel.setFont(font)
        self.multiMainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.multiMainLabel.setObjectName("multiMainLabel")
        self.midLine = QtWidgets.QFrame(self.centralwidget)
        self.midLine.setGeometry(QtCore.QRect(0, 250, 601, 21))
        self.midLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.midLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.midLine.setObjectName("midLine")
        self.lineLabelMulti = QtWidgets.QLabel(self.centralwidget)
        self.lineLabelMulti.setGeometry(QtCore.QRect(80, 310, 441, 2))
        self.lineLabelMulti.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineLabelMulti.setText("")
        self.lineLabelMulti.setObjectName("lineLabelMulti")
        self.lineLabelSing = QtWidgets.QLabel(self.centralwidget)
        self.lineLabelSing.setGeometry(QtCore.QRect(90, 40, 420, 2))
        self.lineLabelSing.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineLabelSing.setText("")
        self.lineLabelSing.setObjectName("lineLabelSing")
        self.translTextEditSing = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.translTextEditSing.setGeometry(QtCore.QRect(210, 90, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.translTextEditSing.setFont(font)
        self.translTextEditSing.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.translTextEditSing.setObjectName("translTextEditSing")
        self.gardTextEditSing = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.gardTextEditSing.setGeometry(QtCore.QRect(10, 90, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gardTextEditSing.setFont(font)
        self.gardTextEditSing.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.gardTextEditSing.setObjectName("gardTextEditSing")
        self.transTextEditSing = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.transTextEditSing.setGeometry(QtCore.QRect(410, 90, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transTextEditSing.setFont(font)
        self.transTextEditSing.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.transTextEditSing.setObjectName("transTextEditSing")
        self.translTextEditMulti = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.translTextEditMulti.setGeometry(QtCore.QRect(210, 370, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.translTextEditMulti.setFont(font)
        self.translTextEditMulti.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.translTextEditMulti.setObjectName("translTextEditMulti")
        self.gardTextEditMulti = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.gardTextEditMulti.setGeometry(QtCore.QRect(10, 370, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gardTextEditMulti.setFont(font)
        self.gardTextEditMulti.setStyleSheet("background-color: rgba(255, 255, 255,95);\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"")
        self.gardTextEditMulti.setObjectName("gardTextEditMulti")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(10, 550, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("\n"
"color: rgb(105, 105, 157);")
        self.statusLabel.setObjectName("statusLabel")
        addWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(addWindow)
        QtCore.QMetaObject.connectSlotsByName(addWindow)

    def retranslateUi(self, addWindow):
        _translate = QtCore.QCoreApplication.translate
        addWindow.setWindowTitle(_translate("addWindow", "MainWindow"))
        self.gardLabelSing.setText(_translate("addWindow", "Gardiners code"))
        self.translLabelSing.setText(_translate("addWindow", "Transliteration"))
        self.TransLabelSing.setText(_translate("addWindow", "Translation"))
        self.singMainLabel.setText(_translate("addWindow", "Add a word with a single meaning."))
        self.addBtnSing.setText(_translate("addWindow", "Add"))
        self.cancelBtnSing.setText(_translate("addWindow", "Cancel"))
        self.translLabelMulti.setText(_translate("addWindow", "Transliteration"))
        self.cancelBtnMulti.setText(_translate("addWindow", "Cancel"))
        self.gardLabelMulti.setText(_translate("addWindow", "Gardiners code"))
        self.transLabelMulti.setText(_translate("addWindow", "Translation"))
        self.addBtnMulti.setText(_translate("addWindow", "Add"))
        self.addBtnListMulti.setText(_translate("addWindow", "Add"))
        self.removeBtnListMulti.setText(_translate("addWindow", "Remove"))
        self.multiMainLabel.setText(_translate("addWindow", "Add a word with multiple meanings."))
        self.statusLabel.setText(_translate("addWindow", "------------------------------------------------------"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addWindow = QtWidgets.QMainWindow()
    ui = Ui_addWindow()
    ui.setupUi(addWindow)
    addWindow.show()
    sys.exit(app.exec_())
