# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dictionaryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dictionaryWindow(object):
    def setupUi(self, dictionaryWindow):
        dictionaryWindow.setObjectName("dictionaryWindow")
        dictionaryWindow.resize(890, 680)
        self.centralwidget = QtWidgets.QWidget(dictionaryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 870, 530))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget{\n"
"background-color: rgba(255, 255, 255,25);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(10, 580, 210, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.addBtn.setFlat(False)
        self.addBtn.setObjectName("addBtn")
        self.removeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtn.setGeometry(QtCore.QRect(230, 580, 210, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.removeBtn.setFont(font)
        self.removeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.removeBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.removeBtn.setFlat(False)
        self.removeBtn.setObjectName("removeBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(450, 580, 210, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.saveBtn.setFlat(False)
        self.saveBtn.setObjectName("saveBtn")
        self.saveAsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveAsBtn.setGeometry(QtCore.QRect(670, 580, 210, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveAsBtn.setFont(font)
        self.saveAsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveAsBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveAsBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.saveAsBtn.setFlat(False)
        self.saveAsBtn.setObjectName("saveAsBtn")
        self.mainBackgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainBackgroundLabel.setGeometry(QtCore.QRect(0, 0, 890, 680))
        self.mainBackgroundLabel.setStyleSheet("\n"
"border-image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13 blurredsmall.png);")
        self.mainBackgroundLabel.setText("")
        self.mainBackgroundLabel.setObjectName("mainBackgroundLabel")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(10, 630, 870, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: rgb(105, 105, 157);")
        self.statusLabel.setObjectName("statusLabel")
        self.changeDictionaryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.changeDictionaryBtn.setGeometry(QtCore.QRect(660, 5, 180, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.changeDictionaryBtn.setFont(font)
        self.changeDictionaryBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeDictionaryBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.changeDictionaryBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.changeDictionaryBtn.setFlat(False)
        self.changeDictionaryBtn.setObjectName("changeDictionaryBtn")
        self.currDictionairyLabel = QtWidgets.QLabel(self.centralwidget)
        self.currDictionairyLabel.setGeometry(QtCore.QRect(10, 0, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.currDictionairyLabel.setFont(font)
        self.currDictionairyLabel.setStyleSheet("color: #333;")
        self.currDictionairyLabel.setObjectName("currDictionairyLabel")
        self.currDictionaryLabelName = QtWidgets.QLabel(self.centralwidget)
        self.currDictionaryLabelName.setGeometry(QtCore.QRect(200, 0, 450, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.currDictionaryLabelName.setFont(font)
        self.currDictionaryLabelName.setStyleSheet("color: rgb(37, 37, 37);\n"
"")
        self.currDictionaryLabelName.setObjectName("currDictionaryLabelName")
        self.statusIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusIconLabel.setGeometry(QtCore.QRect(850, 5, 31, 29))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.statusIconLabel.setFont(font)
        self.statusIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusIconLabel.setObjectName("statusIconLabel")
        self.mainBackgroundLabel.raise_()
        self.listWidget.raise_()
        self.addBtn.raise_()
        self.removeBtn.raise_()
        self.saveBtn.raise_()
        self.saveAsBtn.raise_()
        self.statusLabel.raise_()
        self.currDictionairyLabel.raise_()
        self.changeDictionaryBtn.raise_()
        self.currDictionaryLabelName.raise_()
        self.statusIconLabel.raise_()
        dictionaryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(dictionaryWindow)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(dictionaryWindow)

    def retranslateUi(self, dictionaryWindow):
        _translate = QtCore.QCoreApplication.translate
        dictionaryWindow.setWindowTitle(_translate("dictionaryWindow", "Dictionary"))
        self.addBtn.setText(_translate("dictionaryWindow", "Add"))
        self.removeBtn.setText(_translate("dictionaryWindow", "Remove"))
        self.saveBtn.setText(_translate("dictionaryWindow", "Save"))
        self.saveAsBtn.setText(_translate("dictionaryWindow", "Save as"))
        self.statusLabel.setText(_translate("dictionaryWindow", "Status------------------------------------------------------------------------------------------------------"))
        self.changeDictionaryBtn.setText(_translate("dictionaryWindow", "Change dictionary"))
        self.currDictionairyLabel.setText(_translate("dictionaryWindow", "Current dictionary:"))
        self.currDictionaryLabelName.setText(_translate("dictionaryWindow", "Dictionairy_TEST"))
        self.statusIconLabel.setText(_translate("dictionaryWindow", "⚪"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dictionaryWindow = QtWidgets.QMainWindow()
    ui = Ui_dictionaryWindow()
    ui.setupUi(dictionaryWindow)
    dictionaryWindow.show()
    sys.exit(app.exec_())
