# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guideWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guideWindow(object):
    def setupUi(self, guideWindow):
        guideWindow.setObjectName("guideWindow")
        guideWindow.resize(869, 610)
        self.centralwidget = QtWidgets.QWidget(guideWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 870, 611))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"        border: 1px solid lightgray;\n"
"        bottom:-1px; \n"
"        background: rgb(245, 245, 245);} \n"
"        QTabBar::tab {\n"
"        background: rgb(230, 230, 230); \n"
"        border: 1px solid lightgray; \n"
"        padding: 8px;\n"
"        min-width:127;\n"
"        min-height: 16;\n"
"        max-height: 32;\n"
"            background-color:  rgb(170, 170, 255);\n"
"            color: rgb(51, 51, 51);} \n"
"        QTabBar::tab:selected { \n"
"        background: rgb(245, 245, 245); \n"
"        margin-top: -1px; \n"
"        background-color:  rgb(105, 105, 157);}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Page1)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 868, 568))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.scrollArea_2.setFont(font)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -2248, 849, 2814))
        self.scrollAreaWidgetContents_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label1_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label1_1.setFont(font)
        self.label1_1.setStyleSheet("\n"
"\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 4px 0px;\n"
"\n"
"image:url(:/icons/ps files/allGuide/maingui.png);")
        self.label1_1.setText("")
        self.label1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_1.setObjectName("label1_1")
        self.gridLayout_3.addWidget(self.label1_1, 0, 0, 1, 1)
        self.label1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("image: url(:/icons/ps files/allGuide/mainguilabels.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 4px 0px")
        self.label1_2.setText("")
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setObjectName("label1_2")
        self.gridLayout_3.addWidget(self.label1_2, 1, 0, 1, 1)
        self.label1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label1_4.setFont(font)
        self.label1_4.setStyleSheet("image: url(:/icons/ps files/allGuide/maingui3.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 4px 0px")
        self.label1_4.setText("")
        self.label1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_4.setObjectName("label1_4")
        self.gridLayout_3.addWidget(self.label1_4, 3, 0, 1, 1)
        self.label1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label1_3.setFont(font)
        self.label1_3.setStyleSheet("image: url(:/icons/ps files/allGuide/maingui2.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 4px 0px")
        self.label1_3.setText("")
        self.label1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_3.setObjectName("label1_3")
        self.gridLayout_3.addWidget(self.label1_3, 2, 0, 1, 1)
        self.label1_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label1_5.setFont(font)
        self.label1_5.setStyleSheet("image: url(:/icons/ps files/allGuide/maingui4.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.label1_5.setText("")
        self.label1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_5.setObjectName("label1_5")
        self.gridLayout_3.addWidget(self.label1_5, 4, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.Page1, "")
        self.Page2 = QtWidgets.QWidget()
        self.Page2.setObjectName("Page2")
        self.label2 = QtWidgets.QLabel(self.Page2)
        self.label2.setGeometry(QtCore.QRect(0, -5, 867, 581))
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label2.setFont(font)
        self.label2.setStyleSheet("image: url(:/icons/ps files/allGuide/moreinfomoreresults.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.label2.setText("")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.tabWidget.addTab(self.Page2, "")
        self.Page3 = QtWidgets.QWidget()
        self.Page3.setObjectName("Page3")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.Page3)
        self.scrollArea_7.setGeometry(QtCore.QRect(0, 0, 868, 568))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.scrollArea_7.setFont(font)
        self.scrollArea_7.setStyleSheet("")
        self.scrollArea_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_7.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, -502, 849, 1136))
        self.scrollAreaWidgetContents_9.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_9)
        self.gridLayout_9.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label3_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label3_1.setFont(font)
        self.label3_1.setStyleSheet("image: url(:/icons/ps files/allGuide/dictionary.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 4px 0px")
        self.label3_1.setText("")
        self.label3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_1.setObjectName("label3_1")
        self.verticalLayout_2.addWidget(self.label3_1)
        self.label3_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label3_2.setFont(font)
        self.label3_2.setStyleSheet("image: url(:/icons/ps files/allGuide/dictionarylabels.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.label3_2.setText("")
        self.label3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_2.setObjectName("label3_2")
        self.verticalLayout_2.addWidget(self.label3_2)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_9)
        self.tabWidget.addTab(self.Page3, "")
        self.Page4 = QtWidgets.QWidget()
        self.Page4.setObjectName("Page4")
        self.label4 = QtWidgets.QLabel(self.Page4)
        self.label4.setGeometry(QtCore.QRect(0, -5, 867, 581))
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label4.setFont(font)
        self.label4.setStyleSheet("\n"
"image: url(:/icons/ps files/allGuide/settings.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.label4.setText("")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.tabWidget.addTab(self.Page4, "")
        self.Page5 = QtWidgets.QWidget()
        self.Page5.setObjectName("Page5")
        self.label5 = QtWidgets.QLabel(self.Page5)
        self.label5.setGeometry(QtCore.QRect(0, -5, 867, 581))
        font = QtGui.QFont()
        font.setPointSize(256)
        self.label5.setFont(font)
        self.label5.setStyleSheet("image: url(:/icons/ps files/allGuide/history.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.label5.setText("")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.tabWidget.addTab(self.Page5, "")
        self.Page6 = QtWidgets.QWidget()
        self.Page6.setObjectName("Page6")
        self.bgLabel = QtWidgets.QLabel(self.Page6)
        self.bgLabel.setGeometry(QtCore.QRect(0, 0, 867, 581))
        font = QtGui.QFont()
        font.setPointSize(256)
        self.bgLabel.setFont(font)
        self.bgLabel.setStyleSheet("image: url(:/icons/ps files/allGuide/background.png);\n"
"min-width:800;\n"
"min-height: 558;\n"
"\n"
"margin: 0px 0px 0px 0px")
        self.bgLabel.setText("")
        self.bgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bgLabel.setObjectName("bgLabel")
        self.titleLabel = QtWidgets.QLabel(self.Page6)
        self.titleLabel.setGeometry(QtCore.QRect(50, 100, 781, 181))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.linkTextArea = QtWidgets.QTextBrowser(self.Page6)
        self.linkTextArea.setGeometry(QtCore.QRect(40, 350, 791, 171))
        self.linkTextArea.setStyleSheet("background-color: rgba(255, 255, 255,25%);")
        self.linkTextArea.setOpenExternalLinks(True)
        self.linkTextArea.setObjectName("linkTextArea")
        self.tabWidget.addTab(self.Page6, "")
        guideWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(guideWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(guideWindow)

    def retranslateUi(self, guideWindow):
        _translate = QtCore.QCoreApplication.translate
        guideWindow.setWindowTitle(_translate("guideWindow", "Guide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page1), _translate("guideWindow", "Page 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page2), _translate("guideWindow", "Page 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page3), _translate("guideWindow", "Page 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page4), _translate("guideWindow", "Page 4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page5), _translate("guideWindow", "Page 5"))
        self.titleLabel.setText(_translate("guideWindow", "Guide video by\n"
"Ammar Abdelwadoud:"))
        self.linkTextArea.setHtml(_translate("guideWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://drive.google.com/file/d/1k_FKNkO9uoJnRH7gdJpkjO0ekCcoAn-F/view?usp=sharing\"><span style=\" font-size:32pt; text-decoration: underline; color:#0000ff;\">https://drive.google.com/file/d/1k_FKNkO9uoJnRH7gdJpkjO0ekCcoAn-F/view?usp=sharing</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page6), _translate("guideWindow", "Page 6"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guideWindow = QtWidgets.QMainWindow()
    ui = Ui_guideWindow()
    ui.setupUi(guideWindow)
    guideWindow.show()
    sys.exit(app.exec_())
