# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 615)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.enRadioBtn.setEnabled(True)
        self.enRadioBtn.setGeometry(QtCore.QRect(30, 560, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enRadioBtn.setFont(font)
        self.enRadioBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enRadioBtn.setStyleSheet("color: rgb(200, 200, 200);")
        self.enRadioBtn.setObjectName("enRadioBtn")
        self.arRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.arRadioBtn.setGeometry(QtCore.QRect(120, 560, 71, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.arRadioBtn.setFont(font)
        self.arRadioBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arRadioBtn.setStyleSheet("color: rgb(200, 200, 200);")
        self.arRadioBtn.setObjectName("arRadioBtn")
        self.guideBtn = QtWidgets.QPushButton(self.centralwidget)
        self.guideBtn.setGeometry(QtCore.QRect(1110, 560, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.guideBtn.setFont(font)
        self.guideBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guideBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.guideBtn.setStyleSheet("QPushButton {\n"
            "color: #333;\n"
            "border: 2px solid rgb(105, 105, 157);\n"
            "border-radius: 10px;\n"
            "border-bottom-right-radius:30px;\n"
            "\n"
            "background: rgba(170, 170, 255,95%)\n}"
            "QPushButton:hover {\n"
            "background: rgb(130, 130, 195);}\n"
            "QPushButton:pressed {\n"
            "border-style: inset;\n"
            "background: rgb(77, 77, 115);}\n")
        self.guideBtn.setFlat(False)
        self.guideBtn.setObjectName("guideBtn")
        self.langComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.langComboBox.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.langComboBox.setFont(font)
        self.langComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            
        self.langComboBox.setDuplicatesEnabled(False)
        self.langComboBox.setObjectName("langComboBox")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 1230, 615))
        self.mainLabel.setStyleSheet("background-color:rgb(179, 179, 213);\n"
"\n"
"border-top-left-radius:75px;\n"
"border-bottom-left-radius:75px;\n"
"border-bottom-right-radius:75px;\n"
"\n"
"image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13be.png);\n"
"\n"
"")
        self.mainLabel.setText("")
        self.mainLabel.setScaledContents(True)
        self.mainLabel.setIndent(-1)
        self.mainLabel.setObjectName("mainLabel")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(1180, 20, 31, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    border-radius: 5px;\n"
"   \n"
"    background:rgba(201, 49, 49,100%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(148, 49, 49);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(124, 49, 49);\n"
"    }")
        self.exitBtn.setObjectName("exitBtn")
        self.minimizeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeBtn.setGeometry(QtCore.QRect(1140, 20, 31, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.minimizeBtn.setFont(font)
        self.minimizeBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    border-radius: 5px;\n"
"   \n"
"    background:rgba(201, 49, 49,100%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(148, 49, 49);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(124, 49, 49);\n"
"    }")
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.en_arTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.en_arTextEdit.setGeometry(QtCore.QRect(20, 70, 591, 221))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.en_arTextEdit.setFont(font)
        self.en_arTextEdit.setStyleSheet("background-color:rgba(255, 255, 255,60%);\n"
"\n"
"border-radius:10px;\n"
"\n"
"\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"\n"
"")
        self.en_arTextEdit.setObjectName("en_arTextEdit")
        self.hieroTextEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.hieroTextEdit_2.setGeometry(QtCore.QRect(620, 70, 591, 221))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.hieroTextEdit_2.setFont(font)
        self.hieroTextEdit_2.setStyleSheet("background-color:rgba(255, 255, 255,60%);\n"
"\n"
"border-radius:10px;\n"
"\n"
"\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"\n"
"")
        self.hieroTextEdit_2.setObjectName("hieroTextEdit_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 340, 1191, 201))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.scrollArea.setFont(font)

        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1187, 197))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.categoryComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.categoryComboBox.setGeometry(QtCore.QRect(120, 300, 521, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.categoryComboBox.setFont(font)
        
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.historyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.historyBtn.setGeometry(QtCore.QRect(980, 560, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.historyBtn.setFont(font)
        self.historyBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.historyBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.historyBtn.setStyleSheet("QPushButton {\n"
            "color: #333;\n"
            "border: 2px solid rgb(105, 105, 157);\n"
            "border-radius: 10px;\n"
            "background: rgba(170, 170, 255,95%)\n}"
            "QPushButton:hover {\n"
            "background: rgb(130, 130, 195);}\n"
            "QPushButton:pressed {\n"
            "border-style: inset;\n"
            "background: rgb(77, 77, 115);}\n")
        self.historyBtn.setFlat(False)
        self.historyBtn.setObjectName("historyBtn")
        self.dicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dicBtn.setGeometry(QtCore.QRect(700, 560, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dicBtn.setFont(font)
        self.dicBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dicBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dicBtn.setStyleSheet("QPushButton {\n"
            "color: #333;\n"
            "border: 2px solid rgb(105, 105, 157);\n"
            "border-radius: 10px;\n"
            "\n"
            "background: rgba(170, 170, 255,95%)\n}"
            "QPushButton:hover {\n"
            "background: rgb(130, 130, 195);}\n"
            "QPushButton:pressed {\n"
            "border-style: inset;\n"
            "background: rgb(77, 77, 115);}\n")
        self.dicBtn.setFlat(False)
        self.dicBtn.setObjectName("dicBtn")
        self.settingsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(850, 560, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settingsBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.settingsBtn.setFlat(False)
        self.settingsBtn.setObjectName("settingsBtn")
        self.categoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.categoryLabel.setGeometry(QtCore.QRect(30, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(560, 570, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(440, 570, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.moreinfoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.moreinfoBtn.setGeometry(QtCore.QRect(1080, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.moreinfoBtn.setFont(font)
        self.moreinfoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.moreinfoBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.moreinfoBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.moreinfoBtn.setFlat(False)
        self.moreinfoBtn.setObjectName("moreinfoBtn")
        self.langComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.langComboBox_2.setGeometry(QtCore.QRect(620, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.langComboBox_2.setFont(font)
        self.langComboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        
        self.langComboBox_2.setDuplicatesEnabled(False)
        self.langComboBox_2.setObjectName("langComboBox_2")
        self.langComboBox_2.addItem("")
        self.langComboBox_2.addItem("")
        self.langComboBox_2.addItem("")
        self.langComboBox_2.addItem("")
        self.moreresultsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.moreresultsBtn.setGeometry(QtCore.QRect(940, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.moreresultsBtn.setFont(font)
        self.moreresultsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.moreresultsBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.moreresultsBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.moreresultsBtn.setFlat(False)
        self.moreresultsBtn.setObjectName("moreresultsBtn")
        self.exchangeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exchangeBtn.setGeometry(QtCore.QRect(570, 30, 40, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeBtn.setFont(font)
        self.exchangeBtn.setStyleSheet("border-image: url(:/icons/icons/exchange.png)")
        self.exchangeBtn.setObjectName("exchangeBtn")
        self.exchangeBtn.setFlat(True)

        self.mainLabel.raise_()
        self.enRadioBtn.raise_()
        self.arRadioBtn.raise_()
        self.guideBtn.raise_()
        self.langComboBox.raise_()
        self.exitBtn.raise_()
        self.minimizeBtn.raise_()
        self.en_arTextEdit.raise_()
        self.hieroTextEdit_2.raise_()
        self.scrollArea.raise_()
        self.categoryComboBox.raise_()
        self.historyBtn.raise_()
        self.dicBtn.raise_()
        self.settingsBtn.raise_()
        self.categoryLabel.raise_()
        self.dateLabel.raise_()
        self.timeLabel.raise_()
        self.moreinfoBtn.raise_()
        self.langComboBox_2.raise_()
        self.moreresultsBtn.raise_()
        self.dateLabel.hide()
        self.timeLabel.hide()
        self.exchangeBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ankh"))
        self.enRadioBtn.setText(_translate("MainWindow", "English"))
        self.arRadioBtn.setText(_translate("MainWindow", "Arabic"))
        self.guideBtn.setText(_translate("MainWindow", "Guide"))
        self.langComboBox.setItemText(0, _translate("MainWindow", " English"))
        self.langComboBox.setItemText(1, _translate("MainWindow", " Hieroglyph"))
        self.langComboBox.setItemText(2, _translate("MainWindow", " Transliteration"))
        self.langComboBox.setItemText(3, _translate("MainWindow", " Gardners code"))
        self.langComboBox.setItemText(4, _translate("MainWindow", " Names (English)"))
        self.langComboBox.setItemText(5, _translate("MainWindow", " Names (Arabic)"))

        self.langComboBox_2.setItemText(0, _translate("MainWindow", " English"))
        self.langComboBox_2.setItemText(1, _translate("MainWindow", " Hieroglyph"))
        self.langComboBox_2.setItemText(2, _translate("MainWindow", " Transliteration"))
        self.langComboBox_2.setItemText(3, _translate("MainWindow", " Gardners code"))
        self.exitBtn.setText(_translate("MainWindow", "X"))
        self.minimizeBtn.setText(_translate("MainWindow", "--"))
        self.en_arTextEdit.setPlaceholderText(_translate("MainWindow", "Type text here."))
        self.hieroTextEdit_2.setPlaceholderText(_translate("MainWindow", "Translated content shows here."))
        self.categoryComboBox.setItemText(0, _translate("MainWindow", "-. All signs"))
        self.categoryComboBox.setItemText(1, _translate("MainWindow", "A. Man and his Occupations"))
        self.categoryComboBox.setItemText(2, _translate("MainWindow", "B. Woman and her Occupations"))
        self.categoryComboBox.setItemText(3, _translate("MainWindow", "C. Anthropomorphic Deities"))
        self.categoryComboBox.setItemText(4, _translate("MainWindow", "D. Parts of the Human Body"))
        self.categoryComboBox.setItemText(5, _translate("MainWindow", "E. Mammals"))
        self.categoryComboBox.setItemText(6, _translate("MainWindow", "F. Parts of Mammals"))
        self.categoryComboBox.setItemText(7, _translate("MainWindow", "G. Birds"))
        self.categoryComboBox.setItemText(8, _translate("MainWindow", "H. Parts of Birds"))
        self.categoryComboBox.setItemText(9, _translate("MainWindow", "I. Amphibious Animals, Reptiles, etc."))
        self.categoryComboBox.setItemText(10, _translate("MainWindow", "K. Fish and Parts of Fish"))
        self.categoryComboBox.setItemText(11, _translate("MainWindow", "L. Invertebrates and Lesser Animals"))
        self.categoryComboBox.setItemText(12, _translate("MainWindow", "M. Trees and Plants"))
        self.categoryComboBox.setItemText(13, _translate("MainWindow", "N. Sky, Earth, Water"))
        self.categoryComboBox.setItemText(14, _translate("MainWindow", "O. Buildings, Parts of Buildings, etc."))
        self.categoryComboBox.setItemText(15, _translate("MainWindow", "P. Ships and Parts of Ships"))
        self.categoryComboBox.setItemText(16, _translate("MainWindow", "Q. Domestics and Funerary Furniture"))
        self.categoryComboBox.setItemText(17, _translate("MainWindow", "R. Temple Furniture and Sacred Emblems"))
        self.categoryComboBox.setItemText(18, _translate("MainWindow", "S. Crowns, Dress, Staves, etc."))
        self.categoryComboBox.setItemText(19, _translate("MainWindow", "T. Warfare, Hunting, Butchery"))
        self.categoryComboBox.setItemText(20, _translate("MainWindow", "U. Agriculture, Crafts, and Professions"))
        self.categoryComboBox.setItemText(21, _translate("MainWindow", "V. Rope, Fiber, Baskets, Bags, etc."))
        self.categoryComboBox.setItemText(22, _translate("MainWindow", "W. Vessels of Stone and Earthenware"))
        self.categoryComboBox.setItemText(23, _translate("MainWindow", "X. Loaves and Cakes"))
        self.categoryComboBox.setItemText(24, _translate("MainWindow", "Y. Writings, Games, Music"))
        self.categoryComboBox.setItemText(25, _translate("MainWindow", "Z. Strokes, Signs derived from Hieratic, Geometrical Figures"))
        self.categoryComboBox.setItemText(26, _translate("MainWindow", "Aa. Unclassified"))
        self.historyBtn.setText(_translate("MainWindow", "History"))
        self.dicBtn.setText(_translate("MainWindow", "Dictionary"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.categoryLabel.setText(_translate("MainWindow", "Category: "))
        self.dateLabel.setText(_translate("MainWindow", "22/22/2222"))
        self.timeLabel.setText(_translate("MainWindow", "00:00 AM"))
        self.moreinfoBtn.setText(_translate("MainWindow", "More info"))
        self.moreresultsBtn.setText(_translate("MainWindow", "More results"))
        self.exchangeBtn.setText(_translate("MainWindow", ""))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
