# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moreResultsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_moreResultsWindow(object):
    def setupUi(self, moreResultsWindow):
        moreResultsWindow.setObjectName("moreResultsWindow")
        moreResultsWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(moreResultsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.mainLabel.setStyleSheet("\n"
"border-image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13 blurredsmall.png);")
        self.mainLabel.setText("")
        self.mainLabel.setObjectName("mainLabel")
        self.textedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textedit.setGeometry(QtCore.QRect(10, 10, 581, 381))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.textedit.setFont(font)
        self.textedit.setStyleSheet("background-color:rgba(255, 255, 255,25%);\n"
"\n"
"\n"
"\n"
"\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"\n"
"")
        self.textedit.setReadOnly(True)
        self.textedit.setObjectName("textedit")
        moreResultsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(moreResultsWindow)
        QtCore.QMetaObject.connectSlotsByName(moreResultsWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "More results"))

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    moreResultsWindow = QtWidgets.QMainWindow()
    ui = Ui_moreResultsWindow()
    ui.setupUi(moreResultsWindow)
    moreResultsWindow.show()
    sys.exit(app.exec_())
