# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moreInfoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_moreInfoWindow(object):
    def setupUi(self, moreInfoWindow):
        moreInfoWindow.setObjectName("moreInfoWindow")
        moreInfoWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(moreInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.mainLabel.setStyleSheet("\n"
"border-image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13 blurredsmall.png);")
        self.mainLabel.setText("")
        self.mainLabel.setObjectName("mainLabel")
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 581, 381))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color:rgba(255, 255, 255,25%);\n"
"\n"
"\n"
"\n"
"\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(105, 105, 157);\n"
"\n"
"")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        moreInfoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(moreInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(moreInfoWindow)

    def retranslateUi(self, moreInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        moreInfoWindow.setWindowTitle(_translate("moreInfoWindow", "More info"))

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    moreInfoWindow = QtWidgets.QMainWindow()
    ui = Ui_moreInfoWindow()
    ui.setupUi(moreInfoWindow)
    moreInfoWindow.show()
    sys.exit(app.exec_())
