# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName("settingsWindow")
        settingsWindow.resize(371, 461)
        self.centralwidget = QtWidgets.QWidget(settingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 371, 461))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("\n"
"border-image: url(:/icons/icons/118Z_2012.w026.n002.13B.p1.13 blurredsmall.png);")
        self.mainLabel.setText("")
        self.mainLabel.setObjectName("mainLabel")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(10, 370, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l7.setFont(font)
        self.l7.setObjectName("l7")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(10, 130, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(10, 10, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.changeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.changeBtn.setGeometry(QtCore.QRect(300, 14, 58, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.changeBtn.setFont(font)
        self.changeBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.changeBtn.setObjectName("changeBtn")
        self.l77 = QtWidgets.QLabel(self.centralwidget)
        self.l77.setGeometry(QtCore.QRect(0, 370, 371, 40))
        self.l77.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l77.setText("")
        self.l77.setObjectName("l77")
        self.showtimeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.showtimeCheckbox.setGeometry(QtCore.QRect(300, 374, 58, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.showtimeCheckbox.setFont(font)
        self.showtimeCheckbox.setStyleSheet(" QCheckBox::indicator:unchecked:hover {\n"
"    border-image:url(:/icons/icons/Toggle off2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
" QCheckBox::indicator:checked:hover {\n"
"    border-image:url(:/icons/icons/Toggle on2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
"QCheckBox::indicator:unchecked {\n"
"    border-image: url(:/icons/icons/Toggle off2.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"    \n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"    \n"
"    border-image: url(:/icons/icons/Toggle on2.png);\n"
"    width:58px;\n"
"    height:32px;\n"
"    }")
        self.showtimeCheckbox.setText("")
        self.showtimeCheckbox.setIconSize(QtCore.QSize(16, 16))
        self.showtimeCheckbox.setObjectName("showtimeCheckbox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(240, 134, 116, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.showdateCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.showdateCheckbox.setGeometry(QtCore.QRect(300, 314, 58, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.showdateCheckbox.setFont(font)
        self.showdateCheckbox.setStyleSheet(" QCheckBox::indicator:unchecked:hover {\n"
"    border-image:url(:/icons/icons/Toggle off2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
" QCheckBox::indicator:checked:hover {\n"
"    border-image:url(:/icons/icons/Toggle on2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
"QCheckBox::indicator:unchecked {\n"
"    border-image: url(:/icons/icons/Toggle off2.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"    \n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"    \n"
"    border-image: url(:/icons/icons/Toggle on2.png);\n"
"    width:58px;\n"
"    height:32px;\n"
"    }")
        self.showdateCheckbox.setText("")
        self.showdateCheckbox.setIconSize(QtCore.QSize(16, 16))
        self.showdateCheckbox.setObjectName("showdateCheckbox")
        self.l66 = QtWidgets.QLabel(self.centralwidget)
        self.l66.setGeometry(QtCore.QRect(0, 310, 371, 40))
        self.l66.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l66.setText("")
        self.l66.setObjectName("l66")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(10, 310, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l6.setFont(font)
        self.l6.setObjectName("l6")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(10, 250, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l5.setFont(font)
        self.l5.setObjectName("l5")
        self.boldtextCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.boldtextCheckbox.setGeometry(QtCore.QRect(300, 254, 58, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.boldtextCheckbox.setFont(font)
        self.boldtextCheckbox.setStyleSheet(" QCheckBox::indicator:unchecked:hover {\n"
"    border-image:url(:/icons/icons/Toggle off2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
" QCheckBox::indicator:checked:hover {\n"
"    border-image:url(:/icons/icons/Toggle on2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
"QCheckBox::indicator:unchecked {\n"
"    border-image: url(:/icons/icons/Toggle off2.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"    \n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"    \n"
"    border-image: url(:/icons/icons/Toggle on2.png);\n"
"    width:58px;\n"
"    height:32px;\n"
"    }")
        self.boldtextCheckbox.setText("")
        self.boldtextCheckbox.setIconSize(QtCore.QSize(16, 16))
        self.boldtextCheckbox.setObjectName("boldtextCheckbox")
        self.l55 = QtWidgets.QLabel(self.centralwidget)
        self.l55.setGeometry(QtCore.QRect(0, 250, 371, 40))
        self.l55.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l55.setText("")
        self.l55.setObjectName("l55")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(10, 190, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setObjectName("l4")
        self.darkmodeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.darkmodeCheckbox.setGeometry(QtCore.QRect(300, 194, 58, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.darkmodeCheckbox.setFont(font)
        self.darkmodeCheckbox.setStyleSheet(" QCheckBox::indicator:unchecked:hover {\n"
"    border-image:url(:/icons/icons/Toggle off2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
" QCheckBox::indicator:checked:hover {\n"
"    border-image:url(:/icons/icons/Toggle on2h.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"} \n"
"QCheckBox::indicator:unchecked {\n"
"    border-image: url(:/icons/icons/Toggle off2.png);\n"
"    width: 58px;\n"
"    height: 32px;\n"
"    \n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"    \n"
"    border-image: url(:/icons/icons/Toggle on2.png);\n"
"    width:58px;\n"
"    height:32px;\n"
"    }")
        self.darkmodeCheckbox.setText("")
        self.darkmodeCheckbox.setIconSize(QtCore.QSize(16, 16))
        self.darkmodeCheckbox.setObjectName("darkmodeCheckbox")
        self.l44 = QtWidgets.QLabel(self.centralwidget)
        self.l44.setGeometry(QtCore.QRect(0, 190, 371, 40))
        self.l44.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l44.setText("")
        self.l44.setObjectName("l44")
        self.l33 = QtWidgets.QLabel(self.centralwidget)
        self.l33.setGeometry(QtCore.QRect(0, 130, 371, 40))
        self.l33.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l33.setText("")
        self.l33.setObjectName("l33")
        self.l11 = QtWidgets.QLabel(self.centralwidget)
        self.l11.setGeometry(QtCore.QRect(0, 10, 371, 40))
        self.l11.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l11.setText("")
        self.l11.setObjectName("l11")
        self.l22 = QtWidgets.QLabel(self.centralwidget)
        self.l22.setGeometry(QtCore.QRect(0, 70, 371, 40))
        self.l22.setStyleSheet("background-color: rgba(255, 255, 255,55);")
        self.l22.setText("")
        self.l22.setObjectName("l22")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(10, 70, 351, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.l2.setFont(font)
        self.l2.setStyleSheet("color: rgb(37, 37, 37);\n"
"")
        self.l2.setObjectName("l2")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(230, 420, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.saveBtn.setFlat(False)
        self.saveBtn.setObjectName("saveBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(300, 420, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid rgb(105, 105, 157);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"     background: rgba(170, 170, 255,95%)\n"
"    \n"
"    \n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(130, 130, 195);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(77, 77, 115);\n"
"    }")
        self.cancelBtn.setFlat(False)
        self.cancelBtn.setObjectName("cancelBtn")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(10, 410, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.mainLabel.raise_()
        self.l11.raise_()
        self.l33.raise_()
        self.l66.raise_()
        self.l77.raise_()
        self.l44.raise_()
        self.l55.raise_()
        self.l7.raise_()
        self.l3.raise_()
        self.l1.raise_()
        self.changeBtn.raise_()
        self.showtimeCheckbox.raise_()
        self.comboBox.raise_()
        self.showdateCheckbox.raise_()
        self.l6.raise_()
        self.l5.raise_()
        self.boldtextCheckbox.raise_()
        self.l4.raise_()
        self.darkmodeCheckbox.raise_()
        self.l22.raise_()
        self.l2.raise_()
        self.saveBtn.raise_()
        self.cancelBtn.raise_()
        self.statusLabel.raise_()
        settingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(settingsWindow)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        _translate = QtCore.QCoreApplication.translate
        settingsWindow.setWindowTitle(_translate("settingsWindow", "Settings"))
        self.l7.setText(_translate("settingsWindow", "Show time:"))
        self.l3.setText(_translate("settingsWindow", "Default language:"))
        self.l1.setText(_translate("settingsWindow", "Default dictionary:"))
        self.changeBtn.setText(_translate("settingsWindow", "Change"))
        self.comboBox.setItemText(0, _translate("settingsWindow", "English"))
        self.comboBox.setItemText(1, _translate("settingsWindow", "Arabic"))
        self.l6.setText(_translate("settingsWindow", "Show date:"))
        self.l5.setText(_translate("settingsWindow", "Bold text: "))
        self.l4.setText(_translate("settingsWindow", "Dark mode: "))
        self.l2.setText(_translate("settingsWindow", "-Current_Dictionary"))
        self.saveBtn.setText(_translate("settingsWindow", "Save"))
        self.cancelBtn.setText(_translate("settingsWindow", "Cancel"))
        self.statusLabel.setText(_translate("settingsWindow", "------------------------------------------------------"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsWindow = QtWidgets.QMainWindow()
    ui = Ui_settingsWindow()
    ui.setupUi(settingsWindow)
    settingsWindow.show()
    sys.exit(app.exec_())
